"""
Media helpers: save generated bytes, MIME sniff, Telegram send selector.

Shared by image/video/vision tasks and the Telegram bridge. Stdlib only.
Telegram Bot API hard-limit for bot uploads is 50MB — we refuse larger
files with a clear error instead of attempting send*.

Imports from: ai_agent.config (WORKSPACE, ensure_ws).
Used by: tasks, telegram, server (optional).
"""
from __future__ import annotations

import mimetypes
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

from ai_agent.config import WORKSPACE, ensure_ws

# Telegram Bot API upload limit for bots (sendPhoto/sendVideo/sendDocument).
TELEGRAM_MAX_BYTES = 50 * 1024 * 1024  # 50 MiB

# Preferred jail-relative folder for generated media (under workspace/).
GENERATED_REL = "workspace/generated"


# ---------------------------------------------------------------------------
# Paths / save
# ---------------------------------------------------------------------------


def generated_dir() -> Path:
    """Absolute path to WORKSPACE/workspace/generated/ (created on demand)."""
    ensure_ws()
    d = WORKSPACE / "workspace" / "generated"
    d.mkdir(parents=True, exist_ok=True)
    return d


def safe_generated_name(stem: str, ext: str) -> str:
    """Build a timestamped basename under generated/ (no path separators)."""
    stem = re.sub(r"[^A-Za-z0-9_-]+", "_", (stem or "media").strip())[:40] or "media"
    ext = (ext or "").lstrip(".")
    if not ext:
        ext = "bin"
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return "%s_%s.%s" % (stem, ts, ext)


def save_generated_bytes(data: bytes, stem: str = "media", ext: str = "", mime: str = "") -> Dict[str, Any]:
    """Write bytes under workspace/generated/; return path/name/mime/size.

    Prefer ext from caller; else guess from mime; else .bin.
    """
    if not data:
        return {"ok": False, "error": "empty media bytes"}
    if not ext and mime:
        ext = _ext_for_mime(mime)
    if not ext:
        ext = "bin"
    name = safe_generated_name(stem, ext)
    path = generated_dir() / name
    path.write_bytes(data)
    detected = mime or detect_mime(path, data)
    return {
        "ok": True,
        "path": str(path),
        "name": name,
        "rel": "%s/%s" % (GENERATED_REL, name),
        "bytes": len(data),
        "mime": detected,
        "download": "/api/download?name=%s" % name,
    }


# ---------------------------------------------------------------------------
# MIME / kind
# ---------------------------------------------------------------------------


_MIME_BY_EXT = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".bmp": "image/bmp",
    ".mp4": "video/mp4",
    ".webm": "video/webm",
    ".mov": "video/quicktime",
    ".mkv": "video/x-matroska",
    ".pdf": "application/pdf",
    ".txt": "text/plain",
    ".md": "text/markdown",
    ".json": "application/json",
}


def _ext_for_mime(mime: str) -> str:
    """Best-effort extension (without dot) for a MIME type."""
    mime = (mime or "").split(";")[0].strip().lower()
    for ext, m in _MIME_BY_EXT.items():
        if m == mime:
            return ext.lstrip(".")
    guessed = mimetypes.guess_extension(mime) or ""
    return guessed.lstrip(".") or "bin"


def detect_mime(path: Optional[Path] = None, data: Optional[bytes] = None) -> str:
    """Sniff MIME from magic bytes, then suffix, then octet-stream."""
    blob = data
    if blob is None and path is not None and path.is_file():
        try:
            blob = path.read_bytes()[:32]
        except OSError:
            blob = None
    if blob:
        if blob.startswith(b"\x89PNG\r\n\x1a\n"):
            return "image/png"
        if blob[:3] == b"\xff\xd8\xff":
            return "image/jpeg"
        if blob[:6] in (b"GIF87a", b"GIF89a"):
            return "image/gif"
        if blob[:4] == b"RIFF" and blob[8:12] == b"WEBP":
            return "image/webp"
        if len(blob) >= 12 and blob[4:8] == b"ftyp":
            return "video/mp4"
        if blob[:4] == b"\x1a\x45\xdf\xa3":
            return "video/webm"
        if blob[:5] == b"%PDF-":
            return "application/pdf"
    if path is not None:
        suf = path.suffix.lower()
        if suf in _MIME_BY_EXT:
            return _MIME_BY_EXT[suf]
        guessed, _ = mimetypes.guess_type(str(path))
        if guessed:
            return guessed
    return "application/octet-stream"


def media_kind(mime: str = "", path: Optional[Path] = None) -> str:
    """Return 'image' | 'video' | 'document' for Telegram send* selection."""
    mime = (mime or "").lower()
    if not mime and path is not None:
        mime = detect_mime(path)
    if mime.startswith("image/"):
        return "image"
    if mime.startswith("video/"):
        return "video"
    # Extension fallback
    if path is not None:
        suf = path.suffix.lower()
        if suf in (".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp"):
            return "image"
        if suf in (".mp4", ".webm", ".mov", ".mkv"):
            return "video"
    return "document"


def check_telegram_size(nbytes: int) -> Optional[str]:
    """Return an error string if over 50MB, else None."""
    if nbytes > TELEGRAM_MAX_BYTES:
        mb = nbytes / (1024 * 1024.0)
        return "File too large for Telegram (%.1f MB > 50 MB limit) — skipped send." % mb
    return None


def telegram_send_selector(mime: str = "", path: Optional[Path] = None) -> str:
    """Which Bot API method: sendPhoto | sendVideo | sendDocument."""
    kind = media_kind(mime, path)
    if kind == "image":
        return "sendPhoto"
    if kind == "video":
        return "sendVideo"
    return "sendDocument"


def load_image_bytes(
    image: Optional[Dict[str, Any]] = None,
    image_name: str = "",
) -> Tuple[Optional[bytes], str, str]:
    """Resolve an image from API payload or workspace basename.

    image: {name, content, encoding=base64|text} or {path}.
    Returns (bytes|None, mime, error).
    """
    from ai_agent.tools import safe_path  # local import avoids cycle at import time

    if image and isinstance(image, dict):
        enc = (image.get("encoding") or "base64").lower()
        content = image.get("content")
        name = Path(str(image.get("name") or "upload.bin")).name
        if content is not None:
            if enc == "base64":
                import base64

                try:
                    raw = base64.b64decode(content)
                except Exception as e:  # noqa: BLE001
                    return None, "", "bad base64 image: %s" % e
            elif isinstance(content, (bytes, bytearray)):
                raw = bytes(content)
            else:
                raw = str(content).encode("utf-8")
            mime = image.get("mime") or detect_mime(Path(name), raw)
            return raw, mime, ""
        # path inside payload
        p = image.get("path") or ""
        if p:
            try:
                target = safe_path(p)
            except PermissionError as e:
                return None, "", str(e)
            if not target.is_file():
                return None, "", "image file not found: %s" % p
            raw = target.read_bytes()
            return raw, detect_mime(target, raw), ""
    name = Path(str(image_name or "")).name
    if name:
        try:
            target = safe_path(name)
        except PermissionError as e:
            return None, "", str(e)
        # Also try under generated/
        if not target.is_file():
            gen = generated_dir() / name
            if gen.is_file():
                target = gen
        if not target.is_file():
            return None, "", "image file not found: %s" % name
        raw = target.read_bytes()
        return raw, detect_mime(target, raw), ""
    return None, "", "image required"
